### ISSUE TITLE
Add support for unveil()

### ISSUE THREAD

**Issue by bruce-hill** [n0la/lua-openbsd#3]
It would be really great if you could add support for [unveil(2)](https://man.openbsd.org/unveil), which was added in OpenBSD 6.4. It should be pretty simple to add, the API is just like `pledge()`-- 2 string arguments and it returns -1/sets `errno` if something goes wrong.

**Comment by n0la** [comment]
I have to admit I haven't used openbsd in a while. But I have added the possibility to call `unveil()` from Lua to the project. Would you mind testing it again for me, before I tag a new release?

**Comment by bruce-hill** [comment]
Looks like it works when I tested on openbsd, thanks! One little thing though, it would be nice to get the error message like with pledge:

```c
    if (ret == -1) {
        lua_pushstring(L, strerror(errno));
        return 2;
    }
```
or alternatively, have both functions return nothing, but produce a Lua error if something goes wrong:
```c
    if (ret == -1) {
        luaL_error(L, "unveil: %s", strerror(errno));
    }
    return 0;
```

**Comment by n0la** [comment]
Good spot. The function now returns `strerror(errno)` if it fails, just like `pledge()` does.

**Comment by n0la** [comment]
The new API is stable I think. Are you contacting `ports@` for an update, or should I?

**Comment by qbit** [comment]
@n0la if you cut a new release, I will bump the port :D

**Comment by n0la** [comment]
Thanks Aaron. I have tagged the next release.

**Comment by n0la** [comment]
Release has been tagged, feature has been added, and @qbit will update port.

**Comment by qbit** [comment]
Updated the port!
