### ISSUE TITLE
nil, nil should be allowed for unveil?

### ISSUE THREAD

**Issue by lehtimikko** [n0la/lua-openbsd#5]
Hi! I couldn't get this to work:

After establishing a collection of path and permissions rules, future
calls to unveil() can be disabled by passing two NULL arguments.

(From the unveil man page.)

**Comment by n0la** [comment]
Servus, and good point. I have added this possibility to the master branch. Can you test this for me to see if it works properly for your use case?

**Comment by lehtimikko** [comment]
Morjesta! Oh yes, working perfecty. Thank you. I'm creating a static web page generator, where the user can create web pages with custom Lua functions in a very limited sandbox.

**Comment by n0la** [comment]
Awesome. I also made a new tag, now I just need to prod ports@ to update the ports tree.
